import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowUpRight } from 'lucide-react';
import { CLASSES } from '@/config/classes';
import { GURU, UPDATES } from '@/config/achievements';
import { PHILOSOPHY } from '@/config/philosophy';
import { SITE } from '@/config/site';
import { ConnectCTA } from '@/components/sections/ConnectCTA';
import { Reveal } from '@/components/ui/Reveal';
import { ButtonLink } from '@/components/ui/ButtonLink';

export default function HomePage() {
  return <>
    <section className="relative z-10 grid min-h-[calc(100svh-76px)] overflow-hidden bg-primary text-surface lg:grid-cols-[1.06fr_.94fr]">
      <div className="relative z-10 flex flex-col justify-center px-6 py-20 md:px-12 lg:pl-[max(3rem,calc((100vw-1296px)/2))]"><p className="mb-8 text-xs text-accent">Classical arts in Chennai</p><h1 className="serif max-w-3xl text-display">Where devotion<br />meets form.</h1><p className="mt-8 max-w-md text-base text-surface/75">A living practice in Bharatanatyam and Carnatic music, guided by Guru {GURU.name}.</p><div className="mt-10"><ButtonLink href="/sadhana">Enter the practice</ButtonLink></div><Link href="#philosophy" aria-label="Scroll to our philosophy" className="mt-16 hidden items-center gap-3 text-xs text-surface/65 lg:flex"><ArrowDown size={15} />Scroll to discover</Link></div>
      <div className="relative min-h-[360px] lg:min-h-full"><Image src="https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=1600&q=90" alt="Classical dancer in a dramatic pool of stage light" fill priority sizes="(max-width: 1024px) 100vw, 48vw" className="object-cover object-center"/><div className="absolute inset-0 bg-gradient-to-r from-primary/45 via-primary/5 to-transparent lg:bg-gradient-to-l lg:from-primary/10 lg:via-transparent lg:to-primary/20"/><div className="absolute bottom-8 left-6 border-l border-accent pl-4 text-xs text-surface md:bottom-12 md:left-10">A practice of presence<br /><span className="text-surface/60">Bharatanatyam and Carnatic music</span></div></div>
    </section>
    <section id="philosophy" className="relative z-10 px-6 py-24 md:px-12 md:py-36"><Reveal className="mx-auto max-w-4xl text-center"><p className="eyebrow">Our philosophy</p><blockquote className="serif mt-8 text-4xl leading-[1.08] text-primary md:text-6xl">“{PHILOSOPHY.homeQuote}”</blockquote><p className="mx-auto mt-8 max-w-prose text-sm text-muted md:text-base">{PHILOSOPHY.homeCopy}</p><Link href="/our-story" className="mt-8 inline-flex items-center gap-2 text-xs font-medium text-primary">Discover our lineage <ArrowUpRight size={14} /></Link></Reveal></section>
    <section className="relative z-10 bg-white/65 px-6 py-20 md:px-12 md:py-28"><div className="mx-auto max-w-[1296px]"><Reveal><p className="eyebrow">Two paths, one practice</p><div className="mt-5 flex flex-wrap items-end justify-between gap-5"><h2 className="serif text-5xl text-primary md:text-6xl">What we offer</h2><Link href="/sadhana" className="text-sm text-muted hover:text-primary">Explore all classes <ArrowUpRight className="ml-2 inline" size={15} /></Link></div></Reveal><div className="mt-12 grid gap-7 md:grid-cols-2">{CLASSES.map((course, index) => <Reveal key={course.id}><article className="group grid min-h-[340px] overflow-hidden bg-surface sm:grid-cols-[.9fr_1.1fr]"><div className={`relative min-h-[260px] ${index === 1 ? 'sm:order-2' : ''}`}><Image src={course.image} alt={course.alt} fill sizes="(max-width: 640px) 100vw, 25vw" className="object-cover transition-transform duration-700 group-hover:scale-[1.03]"/></div><div className="flex flex-col justify-between p-7 md:p-8"><div><span className="text-xs text-muted">0{index + 1} / Discipline</span><h3 className="serif mt-5 text-4xl text-primary">{course.name}</h3><p className="mt-3 text-sm text-muted">{course.intro}</p></div><Link href="/sadhana" className="mt-8 inline-flex items-center gap-2 text-sm text-primary">Learn more <ArrowUpRight size={15} /></Link></div></article></Reveal>)}</div></div></section>
    <section className="relative z-10 px-6 py-20 md:px-12 md:py-32"><div className="mx-auto grid max-w-[1296px] gap-12 md:grid-cols-[.9fr_1.1fr] md:items-center"><Reveal className="relative mx-auto aspect-[4/5] w-full max-w-md"><Image src={GURU.portrait} alt={GURU.alt} fill sizes="(max-width: 768px) 90vw, 40vw" className="object-cover"/><span className="absolute -bottom-5 -left-5 -z-10 size-2/3 border border-accent"/></Reveal><Reveal><p className="eyebrow">The guiding presence</p><h2 className="serif mt-5 text-5xl text-primary md:text-6xl">Meet your guru</h2><h3 className="serif mt-6 text-3xl">{GURU.name}</h3>{GURU.bio.map((paragraph) => <p key={paragraph} className="mt-4 max-w-prose text-sm text-muted md:text-base">{paragraph}</p>)}<p className="serif mt-8 border-l border-accent pl-5 text-2xl italic text-primary">“{GURU.quote}”</p><div className="mt-8"><ButtonLink href="/our-story" variant="dark">Read our story</ButtonLink></div></Reveal></div></section>
    <section className="relative z-10 bg-white/65 px-6 py-20 md:px-12 md:py-28"><div className="mx-auto grid max-w-[1296px] gap-12 md:grid-cols-[.7fr_1.3fr]"><Reveal><p className="eyebrow">Notes from our world</p><h2 className="serif mt-5 text-5xl text-primary">Latest from<br />the stage</h2></Reveal><div>{UPDATES.map((update) => <Reveal key={update.title}><article className="grid gap-2 border-b border-primary/15 py-6 sm:grid-cols-[150px_1fr]"><p className="pt-1 text-xs text-muted">{update.date}</p><div><h3 className="serif text-2xl text-primary">{update.title}</h3><p className="mt-2 text-sm text-muted">{update.copy}</p></div></article></Reveal>)}</div></div></section>
    <ConnectCTA title={`There is a place for you in this practice.`} button="Begin your journey" />
  </>;
}
