// TODO: update with actual content
export const CLASSES = [
  { id: 'bharatanatyam', name: 'Bharatanatyam', pronunciation: 'The language of movement', image: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=1200&q=85', alt: 'Classical dancer performing beneath warm stage lights', intro: 'A complete practice in rhythm, geometry and storytelling, rooted in the living repertoire of Bharatanatyam.', paragraphs: ['Students build a strong foundation through adavus, learning posture, footwork and the relationship between movement and tala.', 'As technique deepens, jathis bring together rhythmic patterns and expressive transitions. Students encounter abhinaya through poetry, gesture and the many shades of a story.', 'The longer journey moves toward the Margam, a thoughtfully paced repertoire that brings together the forms and ideas of the dance tradition.'], sequence: ['Adavus', 'Jathis', 'Abhinaya', 'Margam'], details: [{ label: 'For', value: 'Children and adults, beginner to advanced' }, { label: 'Schedule', value: 'Small weekly batches; timings shared on enquiry' }, { label: 'Fees', value: 'Shared directly with families' }] },
  { id: 'carnatic', name: 'Carnatic Music', pronunciation: 'A practice of raga and resonance', image: 'https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1200&q=85', alt: 'Musician holding a classical string instrument', intro: 'A close study of melody, rhythm and listening, shaped by the rich repertoire of South Indian classical music.', paragraphs: ['Voice students begin with breath, pitch and the foundational Sarali Varisai exercises. These first steps build steadiness and confidence in sruti.', 'Lessons gradually open into alankaras, geethams and krithis, with attention to raga, tala, pronunciation and the meaning carried by each composition.', 'Instrumental study can be discussed when you enquire. Every student is encouraged to listen deeply and develop an independent, lifelong relationship with music.'], sequence: ['Sruti & breath', 'Sarali Varisai', 'Geethams', 'Krithis'], details: [{ label: 'For', value: 'Young learners and adults at every stage' }, { label: 'Format', value: 'Individual attention in small groups' }, { label: 'Fees', value: 'Shared directly on enquiry' }] },
] as const;

export const CLASS_LOGISTICS = [
  { label: 'Class size', value: 'Small batches with room for individual guidance.' },
  { label: 'Duration', value: 'Session lengths are shared when you enquire.' },
  { label: 'Mode', value: 'In-person learning in Chennai; ask us about online possibilities.' },
  { label: 'Location', value: 'Chennai, Tamil Nadu. Exact details shared on enquiry.' },
] as const;
